# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name:  Kevin Reyes
title: Backend Developer
email: reyeskevin707+github@gmail.com
website: https://kvrnn.github.io/

# Social links
twitter_username: kvrnnnnnnnnn
github_username:  kvrnn
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: kvrnnnnnnnnn
linkedin_username: kevin-reyes-966a22157
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
quote: >
  Bi-Lingual High Achieving High School Student with a passion for Computer Science and Information Security, experienced with Computers on the Hardware and Software level.
about_content: | # this will include new lines to allow paragraphs
    My name is Kevin and I am a Backend Developer with exprinece in <mark>Python</mark>,<mark>Nodejs</mark>,<mark>React</mark>, and other usual extentions of those languges like <mark>Express.js</mark>, <mark>MongoDB</mark>, <mark>PHP</mark>, <mark>HTML</mark>, and <mark>CSS</mark>.
    Also experinced in secure apis with mern stacks.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
